spring:
  application:
    name: onz-data

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    h2:
      console:
        enabled: true
        path: /h2-console

    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true

  jpa:
    enabled: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

keys:
  kakao-local-api: ${KAKAO_KEY}
  google-place-api: ${GOOGLE_KEY}

webdriver:
  path: ${WEB_DRIVER_PATH}